- id: '1620942755163'
  alias: Snapshot Bedroom Camera
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /5
  condition: []
  action:
  - service: camera.snapshot
    target:
      entity_id: camera.bedroom_camera
    data:
      filename: /media/bedroom_snapshot.jpg
  mode: single
- id: '1621168979014'
  alias: Sync state for bedroom color lights when turned off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 413a6470d1d3c76ffc807b8b5b4a4900
    entity_id: light.bedroom_bedside_lamp
    domain: light
  - platform: device
    type: turned_off
    device_id: 55deb9c45c082073b2eaa94b8ff3c005
    entity_id: light.bedroom_tv_backlight
    domain: light
  - platform: device
    type: turned_off
    device_id: 214fcadebd67f7c214cda88edc03b915
    entity_id: light.bedroom_desk_backlight
    domain: light
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.bedroom_color_lights
  mode: single
- id: '1621169189490'
  alias: Sync bedroom lights effect to rainbow when turned on
  description: ''
  trigger:
  - platform: state
    entity_id: light.bedroom_color_lights
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.bedroom_color_lights
    data:
      effect: rainbow
  mode: single
