- id: '1620942755163'
  alias: Snapshot Bedroom Camera
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /5
  condition: []
  action:
  - service: camera.snapshot
    target:
      entity_id: camera.bedroom_camera
    data:
      filename: /media/bedroom_snapshot.jpg
  mode: single
