
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  allowlist_external_dirs:
    - /media
    - /tmp
  customize: !include customize.yaml

device_tracker:
  - platform: bluetooth_tracker
    track_new_devices: yes
  - platform: bluetooth_le_tracker
    track_new_devices: yes
