
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml
  customize_domains:
    climate:
      swing_modes: ['off', 'vertical']
      hvac_modes: ['off', 'cool', 'heat', 'heat_cool', 'fan_only', 'dry']

device_tracker:
  - platform: bluetooth_le_tracker
