
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  allowlist_external_dirs:
    - /media
    - /tmp
  customize: !include customize.yaml

light:
  - platform: group
    name: Bedroom Color Lights
    entities:
    - light.bedroom_tv_light
    - light.bedroom_bedside_lamp
    - light.bedroom_under_desk_light