# ------------------
# - ESPHOME
# ------------------

substitutions:
  host: demo_rgb
  name: Demo RGB
  area: Demo

packages:
  common: !include .common.yaml

esphome:
  platform: esp32
  board: nodemcu-32s

status_led:
  pin: 2
  
esp32_ble_tracker:

# text_sensor:
#   - platform: ble_scanner
#     name: "BLE Devices Scanner"

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: 4
    num_leds: 13
    rgb_order: GRB
    name: $area RGB
    effects: !include .light_effects.yaml

sensor:
  - platform: dht
    pin: 5
    temperature:
      id: temperature
      name: $area Temperature
    humidity:
      id: humidity
      name: $area Humidity

binary_sensor:
  - platform: gpio
    pin: 12
    name: $area Motion
    device_class: motion

remote_transmitter:
  pin: 13
  id: ir_tx
  carrier_duty_percent: 50%

remote_receiver:
  id: ir_rx
  pin:
    number: 14
    inverted: True
    mode: INPUT_PULLUP
  tolerance: 55%

climate:
  - platform: daikin
    name: $area AC
    sensor: temperature
    transmitter_id: ir_tx
    receiver_id: ir_rx
    visual:
      min_temperature: 18 °C
      max_temperature: 25 °C
      temperature_step: 1 °C
