
# ------------------
# - ESPHOME
# ------------------

packages:
  common: !include .common.yaml

substitutions:
  led: '2'
  host: plug
  name: Plug

esphome:
  name: $host
  platform: ESP8266
  board: esp12e
  esp8266_restore_from_flash: yes
  # name_add_mac_suffix: true
  platformio_options:
    board_build.f_cpu: 160000000L

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: 5
    num_leds: 13
    rgb_order: GRB
    name: $name Light
    effects: !include .light_effects.yaml

sensor:
  - platform: dht
    pin: 4
    temperature:
      id: temperature
      name: $name Temperature
    humidity:
      id: humidity
      name: $name Humidity

binary_sensor:
  - platform: gpio
    pin: 5
    name: $name Motion
    device_class: motion

remote_transmitter:
  pin: 13
  id: ir_tx
  carrier_duty_percent: 50%

remote_receiver:
  id: ir_rx
  pin:
    number: 14
    inverted: True
    mode: INPUT_PULLUP
  tolerance: 55%

climate:
  - platform: daikin
    name: $name AC
    # sensor: temperature
    transmitter_id: ir_tx
    receiver_id: ir_rx
    visual:
      min_temperature: 18 °C
      max_temperature: 25 °C
      temperature_step: 1 °C
