substitutions:
  led: GPIO2
  host: esphome
  addr: $host

esphome:
  name: $host
  board: esp12e
  platform: ESP8266
  build_path: build/$host
  name_add_mac_suffix: yes
  esp8266_restore_from_flash: yes
  platformio_options:
    upload_speed: 460800
    board_build.filesystem: littlefs
    # board_build.ldscript: eagle.flash.4m.ld
    board_build.f_cpu: 160000000L
    board_build.f_flash: 80000000L

# ------------------
# - COMMON FEATURES
# ------------------

status_led:
  pin:
    number: $led
    inverted: true

captive_portal:

web_server:

logger:
  # baud_rate: 0

ota:

api:
  reboot_timeout: 0s
  services:
  - service: restart
    then:
      lambda: 'ESP.restart();'

# ------------------
# - WIFI NETWORK 
# ------------------

wifi:
  power_save_mode: NONE
  # fast_connect: true
  domain: ''
  networks: !secret wifi_networks
  ap:
    ap_timeout: 5s
    ssid: ${host}_AP

# text_sensor:
#   - platform: wifi_info
#     ip_address:
#       name: $name IP Address
#     ssid:
#       name: $name Connected SSID
#     bssid:
#       name: $name Connected BSSID
#     mac_address:
#       name: $name Mac Address

# switch:
#   - platform: restart
#     name: $name Restart
