substitutions:
  led: GPIO2

esphome:
  name: $host
  build_path: build/$host
  platformio_options:
    upload_speed: 460800
    board_build.f_cpu: 160000000L
    board_build.f_flash: 80000000L

# ------------------
# - COMMON FEATURES
# ------------------

status_led:
  pin:
    number: $led
    inverted: true

captive_portal:

web_server:

logger:
  baud_rate: 0

ota:

api:
  services:
  - service: restart
    then:
      lambda: 'ESP.restart();'

# ------------------
# - WIFI NETWORK 
# ------------------

wifi:
  power_save_mode: NONE
  fast_connect: true
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_psk
  ap:
    ssid: $name

# text_sensor:
#   - platform: wifi_info
#     ip_address:
#       name: $name IP Address
#     ssid:
#       name: $name Connected SSID
#     bssid:
#       name: $name Connected BSSID
#     mac_address:
#       name: $name Mac Address

# switch:
#   - platform: restart
#     name: $name Restart
