# ------------------
# - ESPHOME
# ------------------

packages:
  base: !include common/switches.yaml

substitutions:
  host: bathroom_switches
  name: Bathroom Switches
  area: Bathroom

# ------------------
# - BINARY SENSORS 
# ------------------

binary_sensor:

- platform: gpio
  id: input_1
  pin:
    number: 14
    inverted: true
  on_press:
  - fan.toggle: fan_1

- platform: gpio
  id: input_2
  pin:
    number: 5
    inverted: true

- platform: gpio
  id: input_3
  pin:
    number: 12
    inverted: true
  on_press:
  - light.toggle: light_1

# ------------------
# - OUTPUTS 
# ------------------

output:

- platform: gpio
  id: output_1
  pin: 4

- platform: gpio
  id: output_2
  pin: 15

- platform: gpio
  id: output_3
  pin: 13

# ------------------
# - FANS 
# ------------------

fan:

- platform: binary
  id: fan_1
  name: $area Fan
  output: output_1

# ------------------
# - LIGHTS
# ------------------

light:

- platform: binary
  id: light_1
  name: $area Light
  output: output_3
