# ------------------
# - SUBSTITUTIONS
# ------------------

substitutions:
  host: bathroom_switches
  name: Bathroom Switches
  area: Bathroom

# ------------------
# - ESPHOME CONFIG
# ------------------

esphome:
  name: $host
  platform: ESP8266
  board: modwifi
  esp8266_restore_from_flash: yes
  arduino_version: LATEST
  platformio_options:
    upload_speed: 921600
    board_build.f_cpu: 160000000L
    board_build.f_flash: 80000000L

# ------------------
# - WIFI NETWORK 
# ------------------

wifi:
  ap:
    ssid: $name

# ------------------
# - COMMON FEATURES
# ------------------

status_led:
  pin:
    number: 16
    inverted: true

captive_portal:

web_server:

logger:

api:

ota:

# ------------------
# - BINARY SENSORS 
# ------------------

binary_sensor:

- platform: gpio
  id: input_1
  pin:
    number: 14
    inverted: true
  on_press:
  - light.toggle: light_1

- platform: gpio
  id: input_2
  pin:
    number: 5
    inverted: true

- platform: gpio
  id: input_3
  pin:
    number: 12
    inverted: true
  on_press:
  - fan.toggle: fan_1

# ------------------
# - OUTPUTS 
# ------------------

output:

- platform: gpio
  id: output_1
  pin: 4

- platform: gpio
  id: output_2
  pin: 15

- platform: gpio
  id: output_3
  pin: 13

# ------------------
# - FANS 
# ------------------

fan:

- platform: binary
  id: fan_1
  name: $area Fan
  output: output_1

# ------------------
# - LIGHTS
# ------------------

light:

- platform: binary
  id: light_1
  name: $area Light
  output: output_3
