# ------------------
# - SUBSTITUTIONS
# ------------------

substitutions:
  host: bedroom_lamp
  name: Bedroom Lamp

# ------------------
# - ESPHOME CONFIG
# ------------------

esphome:
  name: $host
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: yes
  arduino_version: LATEST
  platformio_options:
    upload_speed: 460800
    board_build.f_cpu: 160000000L
    board_build.f_flash: 80000000L

# ------------------
# - WIFI NETWORK 
# ------------------

wifi:
  ap:
    ssid: $name

# ------------------
# - COMMON FEATURES
# ------------------

status_led:
  pin:
    number: 16
    inverted: true

captive_portal:

web_server:

logger:

api:

ota:


# ------------------
# - LIGHTS
# ------------------

light:

  - platform: fastled_clockless
    chipset: WS2812B
    pin: D1
    num_leds: 10
    rgb_order: GRB
    name: $name
