# ------------------
# - ESPHOME
# ------------------

packages:
  common: !include common/camera.yaml

substitutions:
  host: bedroom_camera
  name: Bedroom Camera
  area: Bedroom

wifi:
  use_address: bedroom_lamp.local

# ------------------
# - CAMERA
# ------------------

esp32_camera:

  name: $area Camera
  external_clock:
    pin: 0
    frequency: 20MHz
  i2c_pins:
    sda: 26
    scl: 27
  data_pins: [5, 18, 19, 21, 36, 39, 34, 35]
  vsync_pin: 25
  href_pin: 23
  pixel_clock_pin: 22
  power_down_pin: 32

  saturation: 0
  brightness: 0
  contrast: 0

  resolution: 1024x768
