# ------------------
# - ESPHOME
# ------------------

packages:
  base: !include common/sonoff.yaml

substitutions:
  host: bedroom_tv
  name: Bedroom TV

api:
  services:
    - service: remote_control
      variables:
        command: int
      then:
      - remote_transmitter.transmit_nec:
          address: 0x02FD
          command: !lambda 'return command;'
          transmitter_id: tx1
      - remote_transmitter.transmit_nec:
          address: 0x02FD
          command: !lambda 'return command;'
          transmitter_id: tx2
    - service: power
      then:
      - remote_transmitter.transmit_nec:
          address: 0x02FD
          command: 0x48B7
          transmitter_id: tx1

remote_transmitter:
- id: tx1
  pin:
    number: 1
    inverted: true
  carrier_duty_percent: 50%
- id: tx2
  pin: GPIO13
  carrier_duty_percent: 50%

# ------------------
# - BINARY SENSORS 
# ------------------

power_supply:
  - id: psu_1
    enable_time: 20ms
    keep_on_time: 5s
    pin: 12 # relay pin

binary_sensor:
  - platform: gpio
    id: btn_1
    pin:
      number: 0
      inverted: true
    on_press:
    - light.toggle: light_1

light:
  - platform: fastled_clockless
    id: light_1
    chipset: UCS1903
    pin: GPIO3
    num_leds: 12
    rgb_order: RGB
    name: $name Backlight
    power_supply: psu_1
    restore_mode: RESTORE_DEFAULT_ON
    effects: !include common/light_effects.yaml
