# ------------------
# - ESPHOME
# ------------------

packages:
  base: !include common/switches.yaml

substitutions:
  host: switches
  name: Switches

wifi:
  use_address: hallway_switches.local

# ------------------
# - BINARY SENSORS 
# ------------------

binary_sensor:

- platform: gpio
  id: input_1
  pin:
    number: 14
    inverted: true
  on_press:
  - light.toggle: light_1

- platform: gpio
  id: input_2
  pin:
    number: 5
    inverted: true
  on_press:
  - light.toggle: light_2

- platform: gpio
  id: input_3
  pin:
    number: 12
    inverted: true
  on_press:
  - light.toggle: light_3

# ------------------
# - OUTPUTS 
# ------------------

output:

- platform: gpio
  id: output_1
  pin: 4

- platform: gpio
  id: output_2
  pin: 15

- platform: gpio
  id: output_3
  pin: 13

# ------------------
# - LIGHTS
# ------------------

light:

- platform: binary
  id: light_1
  name: Switch A
  output: output_1

- platform: binary
  id: light_2
  name: Switch B
  output: output_2

- platform: binary
  id: light_3
  name: Switch C
  output: output_3
