# ------------------
# - ESPHOME
# ------------------

packages:
  base: !include common/switches.yaml

substitutions:
  host: living_room_switches
  name: Living Room Switches
  area: Living Room

# ------------------
# - BINARY SENSORS 
# ------------------

binary_sensor:

- platform: gpio
  id: input_1
  pin:
    number: 14
    inverted: true
  on_press:
  - light.toggle: light_1

- platform: gpio
  id: input_2
  pin:
    number: 5
    inverted: true
  on_press:
  - light.toggle: light_2

- platform: gpio
  id: input_3
  pin:
    number: 12
    inverted: true
  on_press:
  - light.toggle: light_3

# ------------------
# - OUTPUTS 
# ------------------

output:

- platform: gpio
  id: output_1
  pin:
    number: 4
    mode: OUTPUT_OPEN_DRAIN
    inverted: false

- platform: gpio
  id: output_2
  pin:
    number: 15
    mode: OUTPUT_OPEN_DRAIN
    inverted: false

- platform: gpio
  id: output_3
  pin:
    number: 13
    mode: OUTPUT_OPEN_DRAIN
    inverted: false

# ------------------
# - LIGHTS
# ------------------

light:

- platform: binary
  id: light_1
  name: $area Light 1
  output: output_1

- platform: binary
  id: light_2
  name: $area Light 2
  output: output_2

- platform: binary
  id: light_3
  name: $area Light 3
  output: output_3
